### PR TITLE
WIP debugging swapchain issue

### PR DESCRIPTION
**Pull request by schell**
Should help with debugging #9

### CODE REVIEW

**Comment by philpax** [comment]
Thanks for the PR! I'd suggest using `tracing` instead of `fast_log` (the former is the de jure standard in the Rust ecosystem, as far as I know) and removing the `vulkan_enable` line - [the spec](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_vulkan_enable2) says it's an alternative:

> This extension is intended as an alternative to [XR_KHR_vulkan_enable](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_vulkan_enable), and does not depend on it.

It could potentially cause conflicts with other runtimes.

**Comment by schell** [comment]
I've found that getting `tracing`, `tracing-subscriber` and `tracing-log` to work well with `log` to be a bit of a pain, which is why I use `fast_log`. `fast_log` gives you some nice filters that let you easily include ore exclude logs produced by dependency crates without a bunch of configuration. Since `wgpu` uses `log` I've found it easier to go this route. I've been playing around with `tracing-log` to try to get the `wgpu` logs out in this branch but it just doesn't seem to be working. There's some magic invocation I'm sure, but it's not the problem I'd like to be working on.

**Comment by schell** [comment]
Seems I had a bug that was panicking early, preventing `wgpu` from getting to print any logs after all! I'll switch to `tracing` for this.

**Comment by philpax** [comment]
Thanks for the PR, by the way! I took the liberty of merging it as the changes were pretty uncontroversial, even if we're still trying to figure out the issue 🙂

**Pull request merged**
